/*
 * Copyright (c) 2018-2019 Snowplow Analytics Ltd. All rights reserved.
 *
 * This program is licensed to you under the Apache License Version 2.0,
 * and you may not use this file except in compliance with the Apache License Version 2.0.
 * You may obtain a copy of the Apache License Version 2.0 at http://www.apache.org/licenses/LICENSE-2.0.
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the Apache License Version 2.0 is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the Apache License Version 2.0 for the specific language governing permissions and limitations there under.
 */
package com.snowplowanalytics.indicative

// Circe
import io.circe.literal._

object Expectations {

  val unfilteredIndicativeEvent = json"""{
    "eventName": "link_click",
    "eventUniqueId": "jon.doe@email.com",
    "eventTime": 1532217837886,
    "properties": {
      "page_urlhost" : "www.snowplowanalytics.com",
      "br_features_realplayer" : null,
      "etl_tstamp" : "2018-07-20T00:01:25.292Z",
      "web_page_inLanguage" : "en-US",
      "dvce_ismobile" : null,
      "geo_latitude" : 37.443604,
      "performance_timing_domContentLoadedEventEnd" : 1415358091309,
      "refr_medium" : null,
      "performance_timing_domainLookupStart" : 1415358090102,
      "ti_orderid" : null,
      "br_version" : null,
      "base_currency" : null,
      "v_collector" : "clj-tomcat-0.1.0",
      "mkt_content" : null,
      "collector_tstamp" : "2018-07-20T00:02:05Z",
      "os_family" : null,
      "performance_timing_unloadEventEnd" : 1415358090287,
      "ti_sku" : null,
      "event_vendor" : "com.snowplowanalytics.snowplow",
      "network_userid" : "ecdff4d0-9175-40ac-a8bb-325c49733607",
      "performance_timing_requestStart" : 1415358090183,
      "br_renderengine" : null,
      "br_lang" : null,
      "tr_affiliation" : null,
      "ti_quantity" : null,
      "ti_currency" : null,
      "geo_country" : "US",
      "user_fingerprint" : "2161814971",
      "performance_timing_responseStart" : 1415358090265,
      "mkt_medium" : null,
      "page_urlscheme" : "http",
      "ua_parser_context_osMinor" : null,
      "ti_category" : null,
      "ua_parser_context_useragentFamily" : "IE",
      "pp_yoffset_min" : null,
      "br_features_quicktime" : null,
      "event" : "unstruct",
      "refr_urlhost" : null,
      "user_ipaddress" : "92.231.54.234",
      "br_features_pdf" : true,
      "page_referrer" : null,
      "ua_parser_context_useragentPatch" : null,
      "doc_height" : null,
      "refr_urlscheme" : null,
      "performance_timing_redirectStart" : 0,
      "geo_region" : "TX",
      "geo_timezone" : null,
      "page_urlfragment" : "4-conclusion",
      "br_features_flash" : false,
      "os_manufacturer" : null,
      "mkt_clickid" : null,
      "ti_price" : null,
      "br_colordepth" : null,
      "web_page_author" : "Fred Blundun",
      "event_format" : "jsonschema",
      "tr_total" : null,
      "pp_xoffset_min" : null,
      "doc_width" : null,
      "geo_zipcode" : "94109",
      "br_family" : null,
      "web_page_datePublished" : "2014-11-06T00:00:00Z",
      "tr_currency" : null,
      "web_page_breadcrumb" : "blog",
      "useragent" : null,
      "event_name" : "link_click",
      "os_name" : null,
      "page_urlpath" : "/product/index.html",
      "br_name" : null,
      "ip_netspeed" : "Cable/DSL",
      "page_title" : "On Analytics",
      "performance_timing_navigationStart" : 1415358089861,
      "ip_organization" : "Bouygues Telecom",
      "performance_timing_domInteractive" : 1415358090886,
      "dvce_created_tstamp" : "2018-07-20T00:03:57.885Z",
      "br_features_gears" : null,
      "dvce_type" : null,
      "dvce_sent_tstamp" : null,
      "se_action" : null,
      "br_features_director" : null,
      "performance_timing_domComplete" : 0,
      "se_category" : null,
      "ti_name" : null,
      "user_id" : "jon.doe@email.com",
      "performance_timing_unloadEventStart" : 1415358090270,
      "refr_urlquery" : null,
      "ua_parser_context_useragentVersion" : "IE 7.0",
      "performance_timing_loadEventStart" : 0,
      "performance_timing_domLoading" : 1415358090270,
      "true_tstamp" : "2018-07-23T00:03:57.886Z",
      "geo_longitude" : -122.4124,
      "mkt_term" : null,
      "v_tracker" : "js-2.1.0",
      "os_timezone" : null,
      "br_type" : null,
      "br_features_windowsmedia" : null,
      "link_click_targetUrl" : "http://www.example.com",
      "event_version" : "1-0-0",
      "ua_parser_context_useragentMajor" : "7",
      "dvce_screenwidth" : null,
      "se_label" : null,
      "domain_sessionid" : "2b15e5c8-d3b1-11e4-b9d6-1681e6b88ec1",
      "performance_timing_connectStart" : 1415358090103,
      "performance_timing_fetchStart" : 1415358089870,
      "domain_userid" : "bc2e92ec6c204a14",
      "page_urlquery" : "id=GTM-DLRG",
      "geo_location" : "37.443604,-122.4124",
      "refr_term" : null,
      "refr_device_tstamp" : null,
      "link_click_elementClasses" : "foreground",
      "link_click_elementId" : "exampleLink",
      "name_tracker" : "cloudfront-1",
      "ua_parser_context_useragentMinor" : "0",
      "tr_tax_base" : null,
      "web_page_keywords" : "snowplow",
      "dvce_screenheight" : null,
      "mkt_campaign" : null,
      "refr_urlfragment" : null,
      "performance_timing_domContentLoadedEventStart" : 1415358090968,
      "tr_shipping" : null,
      "tr_shipping_base" : null,
      "br_features_java" : null,
      "br_viewwidth" : null,
      "geo_city" : "New York",
      "web_page_genre" : "blog",
      "br_viewheight" : null,
      "refr_domain_userid" : null,
      "br_features_silverlight" : null,
      "ti_price_base" : null,
      "tr_tax" : null,
      "br_cookies" : null,
      "tr_total_base" : null,
      "refr_urlport" : null,
      "derived_tstamp" : "2018-07-22T00:03:57.886Z",
      "app_id" : "angry-birds",
      "ip_isp" : "FDN Communications",
      "ua_parser_context_deviceFamily" : "Other",
      "geo_region_name" : "Florida",
      "ua_parser_context_osPatch" : null,
      "pp_yoffset_max" : null,
      "ip_domain" : "nuvox.net",
      "performance_timing_connectEnd" : 1415358090183,
      "domain_sessionidx" : 3,
      "pp_xoffset_max" : null,
      "mkt_source" : null,
      "page_urlport" : 80,
      "se_property" : null,
      "platform" : "web",
      "ua_parser_context_osFamily" : "Windows XP",
      "performance_timing_loadEventEnd" : 0,
      "event_id" : "c6124-b53a-4b13-a233-0088f79dcbcb",
      "refr_urlpath" : null,
      "mkt_network" : null,
      "performance_timing_redirectEnd" : 0,
      "ua_parser_context_osMajor" : null,
      "ua_parser_context_osPatchMinor" : null,
      "ua_parser_context_osVersion" : "Windows XP",
      "performance_timing_domainLookupEnd" : 1415358090102,
      "se_value" : null,
      "page_url" : "http://www.snowplowanalytics.com",
      "etl_tags" : null,
      "tr_orderid" : null,
      "tr_state" : null,
      "txn_id" : 41828,
      "performance_timing_responseEnd" : 1415358090265,
      "refr_source" : null,
      "tr_country" : null,
      "tr_city" : null,
      "doc_charset" : null,
      "event_fingerprint" : "e3dbfa9cca0412c3d4052863cefb547f",
      "v_etl" : "serde-0.5.2"
    }
  }"""

  val indicativeEventWithTrimmedAtomicFields = json"""
      {
        "eventName": "link_click",
        "eventUniqueId": "jon.doe@email.com",
        "eventTime": 1532217837886,
        "properties": {
           "page_urlhost" : "www.snowplowanalytics.com",
           "web_page_inLanguage" : "en-US",
           "performance_timing_domContentLoadedEventEnd" : 1415358091309,
           "refr_medium" : null,
           "performance_timing_domainLookupStart" : 1415358090102,
           "ti_orderid" : null,
           "br_version" : null,
           "base_currency" : null,
           "mkt_content" : null,
           "os_family" : null,
           "performance_timing_unloadEventEnd" : 1415358090287,
           "ti_sku" : null,
           "network_userid" : "ecdff4d0-9175-40ac-a8bb-325c49733607",
           "performance_timing_requestStart" : 1415358090183,
           "br_renderengine" : null,
           "br_lang" : null,
           "tr_affiliation" : null,
           "ti_quantity" : null,
           "ti_currency" : null,
           "geo_country" : "US",
           "performance_timing_responseStart" : 1415358090265,
           "mkt_medium" : null,
           "ua_parser_context_osMinor" : null,
           "ti_category" : null,
           "ua_parser_context_useragentFamily" : "IE",
           "refr_urlhost" : null,
           "user_ipaddress" : "92.231.54.234",
           "page_referrer" : null,
           "ua_parser_context_useragentPatch" : null,
           "performance_timing_redirectStart" : 0,
           "geo_region" : "TX",
           "geo_timezone" : null,
           "os_manufacturer" : null,
           "ti_price" : null,
           "web_page_author" : "Fred Blundun",
           "tr_total" : null,
           "geo_zipcode" : "94109",
           "br_family" : null,
           "web_page_datePublished" : "2014-11-06T00:00:00Z",
           "web_page_breadcrumb" : "blog",
           "useragent" : null,
           "os_name" : null,
           "page_urlpath" : "/product/index.html",
           "br_name" : null,
           "page_title" : "On Analytics",
           "performance_timing_navigationStart" : 1415358089861,
           "performance_timing_domInteractive" : 1415358090886,
           "dvce_type" : null,
           "se_action" : null,
           "performance_timing_domComplete" : 0,
           "se_category" : null,
           "ti_name" : null,
           "user_id" : "jon.doe@email.com",
           "performance_timing_unloadEventStart" : 1415358090270,
           "ua_parser_context_useragentVersion" : "IE 7.0",
           "performance_timing_loadEventStart" : 0,
           "performance_timing_domLoading" : 1415358090270,
           "mkt_term" : null,
           "os_timezone" : null,
           "br_type" : null,
           "link_click_targetUrl" : "http://www.example.com",
           "ua_parser_context_useragentMajor" : "7",
           "se_label" : null,
           "domain_sessionid" : "2b15e5c8-d3b1-11e4-b9d6-1681e6b88ec1",
           "performance_timing_connectStart" : 1415358090103,
           "performance_timing_fetchStart" : 1415358089870,
           "domain_userid" : "bc2e92ec6c204a14",
           "geo_location" : "37.443604,-122.4124",
           "refr_term" : null,
           "link_click_elementClasses" : "foreground",
           "link_click_elementId" : "exampleLink",
           "ua_parser_context_useragentMinor" : "0",
           "tr_tax_base" : null,
           "web_page_keywords" : "snowplow",
           "mkt_campaign" : null,
           "performance_timing_domContentLoadedEventStart" : 1415358090968,
           "tr_shipping" : null,
           "tr_shipping_base" : null,
           "geo_city" : "New York",
           "web_page_genre" : "blog",
           "ti_price_base" : null,
           "tr_tax" : null,
           "tr_total_base" : null,
           "app_id" : "angry-birds",
           "ua_parser_context_deviceFamily" : "Other",
           "geo_region_name" : "Florida",
           "ua_parser_context_osPatch" : null,
           "performance_timing_connectEnd" : 1415358090183,
           "domain_sessionidx" : 3,
           "mkt_source" : null,
           "se_property" : null,
           "platform" : "web",
           "ua_parser_context_osFamily" : "Windows XP",
           "performance_timing_loadEventEnd" : 0,
           "event_id" : "c6124-b53a-4b13-a233-0088f79dcbcb",
           "refr_urlpath" : null,
           "mkt_network" : null,
           "performance_timing_redirectEnd" : 0,
           "ua_parser_context_osMajor" : null,
           "ua_parser_context_osPatchMinor" : null,
           "ua_parser_context_osVersion" : "Windows XP",
           "performance_timing_domainLookupEnd" : 1415358090102,
           "se_value" : null,
           "page_url" : "http://www.snowplowanalytics.com",
           "tr_orderid" : null,
           "tr_state" : null,
           "performance_timing_responseEnd" : 1415358090265,
           "refr_source" : null,
           "tr_country" : null,
           "tr_city" : null
         }
      }
    """

  val indicativeEventWithTrimmedContextFields = json"""{
    "eventName": "link_click",
    "eventUniqueId": "jon.doe@email.com",
    "eventTime": 1532217837886,
    "properties": {
       "page_urlhost" : "www.snowplowanalytics.com",
       "br_features_realplayer" : null,
       "etl_tstamp" : "2018-07-20T00:01:25.292Z",
       "dvce_ismobile" : null,
       "geo_latitude" : 37.443604,
       "refr_medium" : null,
       "ti_orderid" : null,
       "br_version" : null,
       "base_currency" : null,
       "v_collector" : "clj-tomcat-0.1.0",
       "mkt_content" : null,
       "collector_tstamp" : "2018-07-20T00:02:05Z",
       "os_family" : null,
       "ti_sku" : null,
       "event_vendor" : "com.snowplowanalytics.snowplow",
       "network_userid" : "ecdff4d0-9175-40ac-a8bb-325c49733607",
       "br_renderengine" : null,
       "br_lang" : null,
       "tr_affiliation" : null,
       "ti_quantity" : null,
       "ti_currency" : null,
       "geo_country" : "US",
       "user_fingerprint" : "2161814971",
       "mkt_medium" : null,
       "page_urlscheme" : "http",
       "ti_category" : null,
       "pp_yoffset_min" : null,
       "br_features_quicktime" : null,
       "event" : "unstruct",
       "refr_urlhost" : null,
       "user_ipaddress" : "92.231.54.234",
       "br_features_pdf" : true,
       "page_referrer" : null,
       "doc_height" : null,
       "refr_urlscheme" : null,
       "geo_region" : "TX",
       "geo_timezone" : null,
       "page_urlfragment" : "4-conclusion",
       "br_features_flash" : false,
       "os_manufacturer" : null,
       "mkt_clickid" : null,
       "ti_price" : null,
       "br_colordepth" : null,
       "event_format" : "jsonschema",
       "tr_total" : null,
       "pp_xoffset_min" : null,
       "doc_width" : null,
       "geo_zipcode" : "94109",
       "br_family" : null,
       "tr_currency" : null,
       "useragent" : null,
       "event_name" : "link_click",
       "os_name" : null,
       "page_urlpath" : "/product/index.html",
       "br_name" : null,
       "ip_netspeed" : "Cable/DSL",
       "page_title" : "On Analytics",
       "ip_organization" : "Bouygues Telecom",
       "dvce_created_tstamp" : "2018-07-20T00:03:57.885Z",
       "br_features_gears" : null,
       "dvce_type" : null,
       "dvce_sent_tstamp" : null,
       "se_action" : null,
       "br_features_director" : null,
       "se_category" : null,
       "ti_name" : null,
       "user_id" : "jon.doe@email.com",
       "refr_urlquery" : null,
       "true_tstamp" : "2018-07-23T00:03:57.886Z",
       "geo_longitude" : -122.4124,
       "mkt_term" : null,
       "v_tracker" : "js-2.1.0",
       "os_timezone" : null,
       "br_type" : null,
       "br_features_windowsmedia" : null,
       "link_click_targetUrl" : "http://www.example.com",
       "event_version" : "1-0-0",
       "dvce_screenwidth" : null,
       "se_label" : null,
       "domain_sessionid" : "2b15e5c8-d3b1-11e4-b9d6-1681e6b88ec1",
       "domain_userid" : "bc2e92ec6c204a14",
       "page_urlquery" : "id=GTM-DLRG",
       "geo_location" : "37.443604,-122.4124",
       "refr_term" : null,
       "refr_device_tstamp" : null,
       "link_click_elementClasses" : "foreground",
       "link_click_elementId" : "exampleLink",
       "name_tracker" : "cloudfront-1",
       "tr_tax_base" : null,
       "dvce_screenheight" : null,
       "mkt_campaign" : null,
       "refr_urlfragment" : null,
       "tr_shipping" : null,
       "tr_shipping_base" : null,
       "br_features_java" : null,
       "br_viewwidth" : null,
       "geo_city" : "New York",
       "br_viewheight" : null,
       "refr_domain_userid" : null,
       "br_features_silverlight" : null,
       "ti_price_base" : null,
       "tr_tax" : null,
       "br_cookies" : null,
       "tr_total_base" : null,
       "refr_urlport" : null,
       "derived_tstamp" : "2018-07-22T00:03:57.886Z",
       "app_id" : "angry-birds",
       "ip_isp" : "FDN Communications",
       "geo_region_name" : "Florida",
       "pp_yoffset_max" : null,
       "ip_domain" : "nuvox.net",
       "domain_sessionidx" : 3,
       "pp_xoffset_max" : null,
       "mkt_source" : null,
       "page_urlport" : 80,
       "se_property" : null,
       "platform" : "web",
       "event_id" : "c6124-b53a-4b13-a233-0088f79dcbcb",
       "refr_urlpath" : null,
       "mkt_network" : null,
       "se_value" : null,
       "page_url" : "http://www.snowplowanalytics.com",
       "etl_tags" : null,
       "tr_orderid" : null,
       "tr_state" : null,
       "txn_id" : 41828,
       "refr_source" : null,
       "tr_country" : null,
       "tr_city" : null,
       "doc_charset" : null,
       "event_fingerprint" : "e3dbfa9cca0412c3d4052863cefb547f",
       "v_etl" : "serde-0.5.2"
    }
  }"""

  val mobileIndicativeEvent = json"""{
    "eventName" : "mobile_event",
    "eventUniqueId" : "d1a1abd2-ad91-4427-877b-b5b6a2d59d7a",
    "eventTime" : 1532217837886,
    "properties" : {
      "page_urlhost" : "www.snowplowanalytics.com",
       "br_features_realplayer" : null,
       "etl_tstamp" : "2018-07-20T00:01:25.292Z",
       "dvce_ismobile" : null,
       "client_session_sessionIndex" : 42,
       "geo_latitude" : 37.443604,
       "mobile_context_osVersion" : "5.0.2",
       "refr_medium" : null,
       "ti_orderid" : null,
       "br_version" : null,
       "base_currency" : null,
       "v_collector" : "clj-tomcat-0.1.0",
       "mkt_content" : null,
       "collector_tstamp" : "2018-07-20T00:02:05Z",
       "os_family" : null,
       "ti_sku" : null,
       "event_vendor" : "com.snowplowanalytics.snowplow",
       "network_userid" : "ecdff4d0-9175-40ac-a8bb-325c49733607",
       "mobile_context_deviceManufacturer" : "samsung",
       "br_renderengine" : null,
       "br_lang" : null,
       "client_session_sessionId" : "5185f442-2e6a-49b8-a6d5-166d6c0bcb44",
       "tr_affiliation" : null,
       "ti_quantity" : null,
       "ti_currency" : null,
       "geo_country" : "US",
       "user_fingerprint" : "2161814971",
       "mkt_medium" : null,
       "page_urlscheme" : "http",
       "ua_parser_context_osMinor" : null,
       "ti_category" : null,
       "ua_parser_context_useragentFamily" : "IE",
       "pp_yoffset_min" : null,
       "br_features_quicktime" : null,
       "event" : "unstruct",
       "refr_urlhost" : null,
       "client_session_previousSessionId" : "55c5d879-97c0-3d38-a08e-5bd983cec5da",
       "user_ipaddress" : "92.231.54.234",
       "mobile_context_androidIdfa" : "0aac993c-aaf4-4a6a-a0bc-011f8af28a93",
       "br_features_pdf" : true,
       "page_referrer" : null,
       "ua_parser_context_useragentPatch" : null,
       "doc_height" : null,
       "refr_urlscheme" : null,
       "geo_region" : "TX",
       "geo_timezone" : null,
       "page_urlfragment" : "4-conclusion",
       "br_features_flash" : false,
       "os_manufacturer" : null,
       "mkt_clickid" : null,
       "ti_price" : null,
       "br_colordepth" : null,
       "event_format" : "jsonschema",
       "tr_total" : null,
       "pp_xoffset_min" : null,
       "doc_width" : null,
       "geo_zipcode" : "94109",
       "br_family" : null,
       "tr_currency" : null,
       "useragent" : null,
       "event_name" : "mobile_event",
       "os_name" : null,
       "page_urlpath" : "/product/index.html",
       "br_name" : null,
       "ip_netspeed" : "Cable/DSL",
       "page_title" : "On Analytics",
       "ip_organization" : "Bouygues Telecom",
       "dvce_created_tstamp" : "2018-07-20T00:03:57.885Z",
       "br_features_gears" : null,
       "dvce_type" : null,
       "dvce_sent_tstamp" : null,
       "se_action" : null,
       "br_features_director" : null,
       "se_category" : null,
       "ti_name" : null,
       "user_id" : null,
       "refr_urlquery" : null,
       "ua_parser_context_useragentVersion" : "IE 7.0",
       "true_tstamp" : "2018-07-23T00:03:57.886Z",
       "geo_longitude" : -122.4124,
       "mkt_term" : null,
       "v_tracker" : "js-2.1.0",
       "os_timezone" : null,
       "br_type" : null,
       "br_features_windowsmedia" : null,
       "event_version" : "1-0-0",
       "ua_parser_context_useragentMajor" : "7",
       "client_session_userId" : "d1a1abd2-ad91-4427-877b-b5b6a2d59d7a",
       "dvce_screenwidth" : null,
       "se_label" : null,
       "domain_sessionid" : "2b15e5c8-d3b1-11e4-b9d6-1681e6b88ec1",
       "mobile_event_id" : "a573776c134a49dc8c7bf5889204747d",
       "domain_userid" : null,
       "page_urlquery" : "id=GTM-DLRG",
       "geo_location" : "37.443604,-122.4124",
       "refr_term" : null,
       "refr_device_tstamp" : null,
       "name_tracker" : "cloudfront-1",
       "ua_parser_context_useragentMinor" : "0",
       "tr_tax_base" : null,
       "dvce_screenheight" : null,
       "mkt_campaign" : null,
       "refr_urlfragment" : null,
       "tr_shipping" : null,
       "tr_shipping_base" : null,
       "br_features_java" : null,
       "br_viewwidth" : null,
       "geo_city" : "New York",
       "br_viewheight" : null,
       "refr_domain_userid" : null,
       "br_features_silverlight" : null,
       "client_session_firstEventId" : "115a70c9-c173-4961-8973-e266b39f5d8a",
       "ti_price_base" : null,
       "tr_tax" : null,
       "br_cookies" : null,
       "tr_total_base" : null,
       "refr_urlport" : null,
       "derived_tstamp" : "2018-07-22T00:03:57.886Z",
       "client_session_storageMechanism" : "SQLITE",
       "app_id" : "angry-birds",
       "ip_isp" : "FDN Communications",
       "mobile_context_osType" : "android",
       "ua_parser_context_deviceFamily" : "Other",
       "geo_region_name" : "Florida",
       "mobile_context_networkType" : "wifi",
       "ua_parser_context_osPatch" : null,
       "pp_yoffset_max" : null,
       "ip_domain" : "nuvox.net",
       "domain_sessionidx" : 3,
       "pp_xoffset_max" : null,
       "mkt_source" : null,
       "page_urlport" : 80,
       "se_property" : null,
       "platform" : "mob",
       "ua_parser_context_osFamily" : "Windows XP",
       "event_id" : "c6124-b53a-4b13-a233-0088f79dcbcb",
       "refr_urlpath" : null,
       "mkt_network" : null,
       "ua_parser_context_osMajor" : null,
       "ua_parser_context_osPatchMinor" : null,
       "ua_parser_context_osVersion" : "Windows XP",
       "se_value" : null,
       "page_url" : "http://www.snowplowanalytics.com",
       "etl_tags" : null,
       "tr_orderid" : null,
       "tr_state" : null,
       "txn_id" : 41828,
       "refr_source" : null,
       "tr_country" : null,
       "tr_city" : null,
       "doc_charset" : null,
       "mobile_context_deviceModel" : "SM-T530NU",
       "event_fingerprint" : "e3dbfa9cca0412c3d4052863cefb547f",
       "v_etl" : "serde-0.5.2"
    }
  }"""

  val userId              = "jon.doe@email.com"
  val clientSessionUserId = "d1a1abd2-ad91-4427-877b-b5b6a2d59d7a"
  val domainUserid        = "bc2e92ec6c204a14"

}
